---
driver:
  name: vagrant
  customize:
    memory: 4000
    ioapic: 'on'
    natdnshostresolver1: "on"
    natdnsproxy1: "on"
  network:
  #- ["forwarded_port", {guest: 8080, host: 9991}]
  - ["forwarded_port", {guest: 9191, host: 9192}]
  - ["forwarded_port", {guest: 8888, host: 8888}]
  - ["forwarded_port", {guest: 8088, host: 10088}]
  - ["forwarded_port", {guest: 8089, host: 8089}]

provisioner:
  name: chef_solo
  require_chef_omnibus: 12.4.3


platforms:
  - name: ubuntu-14.04
    run_list:
     - recipe[apt]
    attributes:
      java:
        jdk_version: 7

suites: 
  - name: default
    run_list:
      - recipe[kagent::install]
      - recipe[kzookeeper::install]
      - recipe[kkafka::install]
      - recipe[apache_hadoop::install]
      - recipe[kzookeeper::default]
      - recipe[kkafka::default]
      - recipe[apache_hadoop::nn]
      - recipe[apache_hadoop::dn]
      - recipe[apache_hadoop::rm]
      - recipe[apache_hadoop::nm]
      - recipe[apache_hadoop::jhs]
      - recipe[kkafka::monitor]
    attributes:
         kkafka:
            default:
                private_ips: ["10.0.2.15"]
            private_ips: ["10.0.2.15"]
         kzookeeper:
            default:
                private_ips: ["10.0.2.15"]
            private_ips: ["10.0.2.15"]
         kagent:
            private_ips: ["10.0.2.15"]
         private_ips: ["10.0.2.15"]
         public_ips: ["10.0.2.15"]
         vagrant: "enabled"
         kafka:
            ulimit_file: 128000
            broker:
              log_dirs: ['/mnt/kafka-logs-1', '/mnt/kafka-logs-2']
              zookeeper_connect: ['localhost:2181']
              zookeeper_connection_timeout_ms: 15_000
         flink:
            mode: streaming
            jobmanager:
               private_ips: ["10.0.2.15"]
               web_port: 8089
            taskmanager:
               private_ips: ["10.0.2.15"]
         hadoop_spark:
            master:
               private_ips: ["10.0.2.15"]
            worker:
               private_ips: ["10.0.2.15"]
         apache_hadoop:
            version: 2.7.1
            group: hadoop
            hdfs:
               user: hdfs
            yarn:
               user: yarn
            nn:
               private_ips: ["10.0.2.15"]
            dn:
               private_ips: ["10.0.2.15"]
            rm:
               private_ips: ["10.0.2.15"]
               public_ips: ["10.0.2.15"]
            nm:
               private_ips: ["10.0.2.15"]
            jhs:
               private_ips: ["10.0.2.15"]

